### ISSUE TITLE
Problem with PR submissions?

### ISSUE THREAD

**Issue by steveraysteveray** [open223/models.open223.info#12] opened 2024-01-03 16:24 UTC
It looks like both Michael P. and I have created PRs from forks of this repo, which are failing because of a permissions problem during the automatic workflow. Questions:

1. Is this the preferred way to add models? (i.e. create a fork and then a PR)?
2. If not, how should we add models?

**Comment by gtfierro** [comment] 2024-01-03 20:38
The issue is that our GitHub action does not differentiate between pull requests and actual commits to the main branch. You were doing everything correctly. We just need to adjust the action to not attempt to push to our _gh-pages_ branch (which serves the book) until after a commit has been merged

**Comment by gtfierro** [comment] 2024-01-03 20:40
This should be fixed now. Let me know if you hit this issue again!

**Closed as completed by gtfierro** 2024-01-03 20:40 UTC
